---
title: "TED"
output: 
  html_document
---

### Context
The data we use in the study are about all audio-video recordings of TED Talks uploaded to the official TED.com website until September 21st, 2017. It contains information about all talks including number of views, number of comments, descriptions, speakers and titles.


### Data description
There are 17 variables in this dataset:

* `name`: The official name of the TED Talk. Includes the title and the speaker.
* `title`: The title of the talk.
* `description`: A blurb of what the talk is about.
* `main_speaker`: The first named speaker of the talk.
* `speaker_occupation`: The occupation of the main speaker.
* `num_speaker`: The number of speakers in the talk.
* `duration`: The duration of the talk in seconds.
* `event`: The TED/TEDx event where the talk took place.
* `film_date`: The Unix timestamp of the filming.
* `published_date`: The Unix timestamp for the publication of the talk on TED.com.
* `comments`: The number of first level comments made on the talk.
* `tags`: The themes associated with the talk.
* `languages`: The number of languages in which the talk is available.
* `ratings`: A stringified dictionary of the various ratings given to the talk (inspiring, fascinating, jaw dropping, etc.)
* `related_talks`: A list of dictionaries of recommended talks to watch next.
* `url`: The URL of the talk.
* `views`: The number of views on the talk.


